/* eslint-disable */
/* AUTO-GENERATED by tools/build-browser-core.mjs — do not edit by hand */
(function (global) {
  const HABITATS = ["forest","marsh","canyon"];
  const PERSONAS = ["liam","aisha","marcus","elena"];
  const SPECIES = [{"id":"cardinal","name":"Northern Cardinal","activity":["dawn","day"]},{"id":"owl","name":"Barred Owl","activity":["dusk","night"]},{"id":"peeper","name":"Spring Peeper","activity":["dawn","night"]},{"id":"cricket","name":"Tree Cricket","activity":["dusk","night"]},{"id":"woodpecker","name":"Pileated Woodpecker","activity":["day"]},{"id":"bat","name":"Big Brown Bat","activity":["dusk","night"]}];
  const SPECIES_FREQ_PROFILES = {"cardinal":{"peaks":[0.28,0.45,0.62],"label":"Whistle band"},"owl":{"peaks":[0.18,0.35],"label":"Low hoot"},"peeper":{"peaks":[0.72,0.82],"label":"High peep"},"cricket":{"peaks":[0.65,0.78],"label":"Chirp rhythm"},"woodpecker":{"peaks":[0.22,0.38,0.52,0.68],"label":"Drum bursts"},"bat":{"peaks":[0.55,0.7],"label":"FM sweep","fm":true}};
  const SPECIES_LORE = {"cardinal":{"structure":"Clear whistled phrases, ~2–3 kHz fundamentals","duty":"Dawn + day chorus","tip":"Repeated 2-note motif; harmonics rise with SNR"},"owl":{"structure":"Low hoots ~300 Hz, 8-syllable rhythm","duty":"Dusk + night","tip":"\"Who-cooks-for-you\" — space hoots ~2 s apart"},"peeper":{"structure":"High peep ~3 kHz, short duty cycle","duty":"Dawn + night at wetlands","tip":"Mass chorus raises noise floor — aim one caller"},"cricket":{"structure":"Rhythmic chirp ~3.1 kHz band","duty":"Dusk + night","tip":"Temperature-linked rate; check spectrogram harmonics"},"woodpecker":{"structure":"Drum bursts 0.5–2 kHz, irregular spacing","duty":"Day only","tip":"Drumming = territory; not song — look for burst pattern"},"bat":{"structure":"FM sweep down-chirp (down-converted)","duty":"Dusk + night","tip":"FM slope visible in Kaleidoscope; not tonal like birds"}};
  const HABITAT_NOISE_FLOOR = {"forest":12,"marsh":18,"canyon":9};
  const TIME_ORDER = ["dawn","day","dusk","night"];
  const FACING_BONUS_THRESHOLD = 1.2;
  const EXPEDITION_REGULAR_TARGET = 4;
  const BOSS_SPECIES_BY_HABITAT = {"forest":"owl","marsh":"peeper","canyon":"woodpecker"};

  function angleDiff(dir, facing) {
  return Math.abs(((dir - facing + Math.PI * 3) % (Math.PI * 2)) - Math.PI);
}
  function scoreAnimalTarget(player, animal, timeOfDay) {
  if (!animal.activity.includes(timeOfDay)) return -999;
  const dx = animal.x - player.x;
  const dy = animal.y - player.y;
  const dist = Math.hypot(dx, dy);
  const dir = Math.atan2(dy, dx);
  const adiff = angleDiff(dir, player.facing);
  const facingScore = player.listenActive ? (1.6 - Math.min(1.2, adiff)) : 0.6;
  return (620 - dist) * 0.9 + facingScore * 180;
}
  function clipQualityFromScore(bestScore) {
  return Math.max(0.35, Math.min(1, bestScore / 650));
}
  function selectRecordingTarget(player, animals, timeOfDay) {
  let best = null;
  let bestScore = -999;
  for (const a of animals) {
    const score = scoreAnimalTarget(player, a, timeOfDay);
    if (score > bestScore) {
      bestScore = score;
      best = a;
    }
  }
  if (!best && animals.length) {
    best = animals[0];
    bestScore = scoreAnimalTarget(player, best, timeOfDay);
  }
  return {
    dominant: best,
    best,
    bestScore,
    quality: clipQualityFromScore(bestScore),
  };
}
  function facingBonusFromDiff(adiff, listenActive) {
  if (!listenActive) return Math.max(0.35, 1 - adiff / Math.PI) * 0.9;
  const align = Math.max(0, 1 - adiff / (Math.PI * 0.42));
  return 0.55 + align * 2.0;
}
  function computeSnrDb(player, animal, listenActive = false) {
  const warmth = computeCallWarmth(player, animal);
  const prox = Math.max(0.08, 1 - warmth.dist / 500);
  const base = listenActive ? 6 + warmth.warmth * 24 : 3 + prox * 8;
  const facingBonus = listenActive ? warmth.facingAlign * 6 : 0;
  const distPenalty = Math.max(0, (warmth.dist - 280) / 45);
  const db = base + facingBonus - distPenalty;
  return Math.round(Math.max(-4, Math.min(32, db)) * 10) / 10;
}
  function computeIdConfidence({ quality, peakTapped, isLikely }) {
  let conf = (quality ?? 0.5) * 55;
  if (peakTapped) conf += 22;
  if (isLikely) conf += 15;
  return Math.round(Math.max(12, Math.min(98, conf)));
}
  function computeCallWarmth(player, animal) {
  const dx = animal.x - player.x;
  const dy = animal.y - player.y;
  const dist = Math.hypot(dx, dy);
  const dirTo = Math.atan2(dy, dx);
  const adiff = angleDiff(dirTo, player.facing || 0);
  const facingAlign = Math.max(0, 1 - adiff / (Math.PI * 0.5));
  const prox = Math.max(0.08, 1 - dist / 500);
  const listenActive = !!player.listenActive;
  const warmth = listenActive
    ? Math.min(1, 0.2 + prox * 0.45 + facingAlign * 0.5)
    : prox * 0.55;
  const vol = Math.min(1.35, warmth * (listenActive ? 1.55 : 0.8));
  const pan = Math.max(-1, Math.min(1, (dx / 380) * (0.55 + facingAlign * 0.55)));
  return { vol, pan, warmth, dist, facingAlign };
}
  function nearestActiveCaller(player, animals, timeOfDay) {
  let animal = null;
  let distance = Infinity;
  for (const a of animals) {
    if (!a.activity.includes(timeOfDay)) continue;
    const d = Math.hypot(a.x - player.x, a.y - player.y);
    if (d < distance) {
      distance = d;
      animal = a;
    }
  }
  return { animal, distance };
}
  function tickAnimals(animals, dt = 1) {
  return animals.map((a) => {
    const bobPhase = (a.bobPhase || 0) + 0.029 * dt;
    return {
      ...a,
      bobPhase,
      x: a.x + Math.sin(bobPhase * 0.65) * 0.38 * dt,
      y: a.y + Math.cos(bobPhase * 0.48) * 0.27 * dt,
    };
  });
}
  function applyDashScare(player, animals) {
  return animals.map((a) => {
    const dx = a.x - player.x;
    const dy = a.y - player.y;
    const dist = Math.hypot(dx, dy);
    if (dist < 120 && dist > 5) {
      const push = (120 - dist) / 8;
      return { ...a, x: a.x + (dx / dist) * push, y: a.y + (dy / dist) * push };
    }
    return { ...a };
  });
}
  function simulateListenFacing(player, animals, timeOfDay, listenActive) {
  if (!listenActive) return { ...player };
  const nearest = nearestActiveCaller(player, animals, timeOfDay);
  if (!nearest.animal) return { ...player };
  return {
    ...player,
    facing: Math.atan2(nearest.animal.y - player.y, nearest.animal.x - player.x),
  };
}
  function initAnimals(habitat = 'forest') {
  const baseY = habitat === 'marsh' ? 340 : habitat === 'canyon' ? 250 : 290;
  const spread = habitat === 'marsh' ? 95 : 110;
  return SPECIES.map((sp, i) => {
    const yJitter = (i % 2) * 55 + (habitat === 'canyon' ? -30 : 0);
    return {
      id: sp.id,
      species: sp,
      x: 130 + i * spread + (habitat === 'canyon' ? i * 3 : 0),
      y: baseY + yJitter,
      activity: sp.activity,
    };
  });
}
  function qualityLabel(quality) {
  if (quality > 0.8) return 'CLEAN';
  if (quality > 0.55) return 'FAIR';
  return 'NOISY';
}
  function integrityGain(quality) {
  return Math.round(3 + quality * 6);
}
  function integrityLoss(quality) {
  return quality > 0.7 ? 8 : 4;
}
  function applyIdentification({
  chosenId,
  dominantId,
  quality,
  logged,
  integrity,
  bossLogged = false,
  habitat = 'forest',
}) {
  const correct = chosenId === dominantId;
  const bossId = getBossSpeciesId(habitat);
  const isBoss = dominantId === bossId;

  if (correct) {
    const gain = integrityGain(quality);
    if (isBoss && logged >= EXPEDITION_REGULAR_TARGET && !bossLogged) {
      return {
        correct: true,
        logged,
        bossLogged: true,
        integrity: Math.min(100, integrity + gain + 5),
        delta: gain + 5,
        isBoss: true,
      };
    }
    if (logged >= EXPEDITION_REGULAR_TARGET && !isBoss) {
      return {
        correct: true,
        logged,
        bossLogged,
        integrity: Math.min(100, integrity + Math.max(2, Math.floor(gain / 2))),
        delta: Math.max(2, Math.floor(gain / 2)),
        bonusLog: true,
      };
    }
    return {
      correct: true,
      logged: Math.min(EXPEDITION_REGULAR_TARGET, logged + 1),
      bossLogged,
      integrity: Math.min(100, integrity + gain),
      delta: gain,
      isBossEarly: isBoss && logged < EXPEDITION_REGULAR_TARGET,
    };
  }
  const loss = integrityLoss(quality);
  return {
    correct: false,
    logged,
    bossLogged,
    integrity: Math.max(35, integrity - loss),
    delta: -loss,
    missSpeciesId: dominantId,
  };
}
  function shouldCompleteExpedition(logged, bossLogged = false) {
  return logged >= EXPEDITION_REGULAR_TARGET && bossLogged;
}
  function getBossSpeciesId(habitat = 'forest') {
  return BOSS_SPECIES_BY_HABITAT[habitat] || 'owl';
}
  function expeditionPhase(logged, bossLogged = false, habitat = 'forest') {
  if (shouldCompleteExpedition(logged, bossLogged)) return 'complete';
  if (logged >= EXPEDITION_REGULAR_TARGET) return 'boss';
  if (logged >= 1) return 'survey';
  return 'explore';
}
  function markHabitatDone(doneList, habitat) {
  const done = [...doneList];
  if (!done.includes(habitat)) done.push(habitat);
  return done;
}
  function personaHint(persona, kind) {
  const hints = {
    liam: {
      miss: 'Miss — get closer and aim the cone!',
      learn: 'Tip: the cone is your superpower.',
    },
    aisha: {
      miss: 'Not quite — try facing the animal while holding Listen.',
      learn: 'Teaching moment: directional mics reduce background noise.',
    },
    marcus: {
      miss: 'ID miss — improve SNR by closing distance + aiming.',
      learn: 'Field tip: log clean clips for your BioBlitz report.',
    },
    elena: {
      miss: 'Incorrect ID — check spectrogram quality and bearing.',
      learn: 'Pro note: integrity reflects recording SNR + correct classification.',
    },
  };
  return (hints[persona] || hints.liam)[kind];
}
  function activeSpeciesForTime(speciesList, timeOfDay) {
  return speciesList.filter((sp) => sp.activity.includes(timeOfDay));
}
  function likelyMatchThreshold(persona) {
  return persona === 'liam' ? 0.48 : 0.52;
}
  function buildIdentifyOptions(speciesList, clip, persona) {
  const pool = activeSpeciesForTime(speciesList, clip.timeOfDay);
  const threshold = likelyMatchThreshold(persona);
  return pool
    .slice()
    .sort((a, b) => (a.id === clip.dominant.id ? -1 : b.id === clip.dominant.id ? 1 : 0))
    .map((sp) => ({
      id: sp.id,
      name: sp.name,
      isLikely: sp.id === clip.dominant.id && clip.quality >= threshold,
    }));
}
  function buildSpectrogramPeaks(clip) {
  const profile = SPECIES_FREQ_PROFILES[clip.dominant?.id] || { peaks: [0.5], label: 'Call band' };
  const q = clip.quality ?? 0.5;
  const jitter = (1 - q) * 0.05;
  return profile.peaks.map((x, i) => ({
    xNorm: Math.max(0.08, Math.min(0.92, x + Math.sin(i * 1.7) * jitter)),
    height: 0.32 + q * 0.42 + (i === 0 ? 0.18 : 0.06),
    isKey: i === 0,
    speciesId: clip.dominant.id,
    label: profile.label,
    fm: !!profile.fm,
  }));
}
  function buildPhenologyMatrix(speciesList = SPECIES) {
  return TIME_ORDER.map((time) => ({
    time,
    species: speciesList.filter((sp) => sp.activity.includes(time)).map((sp) => sp.id),
    count: speciesList.filter((sp) => sp.activity.includes(time)).length,
  }));
}
  function suggestPhenologyTime({ speciesList, timeOfDay, loggedIds = [] }) {
  const matrix = buildPhenologyMatrix(speciesList);
  let best = timeOfDay;
  let bestScore = -1;
  for (const row of matrix) {
    const unlogged = row.species.filter((id) => !loggedIds.includes(id)).length;
    const score = unlogged * 2 + row.count;
    if (score > bestScore) {
      bestScore = score;
      best = row.time;
    }
  }
  return { time: best, matrix };
}
  function buildClipManifest(entries, meta = {}) {
  const header = 'timestamp,habitat,time_of_day,species_id,species_name,quality,snr_db,correct,confidence';
  const rows = entries.map((e, i) => {
    const sp = e.species || {};
    const id = sp.id || sp;
    const name = sp.name || id;
    return [
      e.timestamp || `clip_${i + 1}`,
      meta.habitat || '',
      e.time || e.timeOfDay || '',
      id,
      `"${String(name).replace(/"/g, '""')}"`,
      e.quality != null ? Math.round(e.quality * 1000) / 1000 : '',
      e.snrDb != null ? e.snrDb : '',
      e.correct ? 'true' : 'false',
      e.confidence != null ? e.confidence : '',
    ].join(',');
  });
  return [header, ...rows].join('\n');
}
  function dailyRareSpecies(date = new Date()) {
  const seed = date.getFullYear() * 1000 + date.getMonth() * 50 + date.getDate();
  const idx = seed % SPECIES.length;
  return SPECIES[idx];
}
  function simIdentificationBonus({ features, persona, quality, skill }) {
  let bonus = 0;
  const threshold = likelyMatchThreshold(persona);
  if (quality >= 0.58 && features.nearestCallerHint && skill >= 0.72) bonus += 0.1;
  if (quality >= 0.55 && features.personaHints && skill >= 0.75) bonus += 0.08;
  if (quality >= 0.62 && features.integrityToasts) bonus += 0.06;
  if (quality >= threshold && features.likelyMatchLabel && skill >= 0.78) {
    bonus += persona === 'liam' ? 0.14 : 0.1;
  }
  if (features.activeSpeciesFilter && quality >= 0.45 && skill >= 0.78) bonus += 0.08;
  if (skill >= 0.9 && quality >= 0.5 && features.likelyMatchLabel) bonus += 0.06;
  if (features.interactiveSpectrogram && quality >= 0.48 && skill >= 0.65) bonus += 0.14;
  if (features.vectorSpeciesArt && skill >= 0.6) bonus += 0.05;
  return bonus;
}

  class FieldSession {
  constructor({ habitat = 'forest', timeOfDay = 'dawn', speciesList = SPECIES, rng = Math.random, dashEnabled = false } = {}) {
    this.rng = rng;
    this.speciesList = speciesList;
    this.dashEnabled = dashEnabled;
    const baseAnimals = initAnimals(habitat);
    let tod = timeOfDay;
    if (baseAnimals.filter((a) => a.activity.includes(tod)).length < 3) {
      tod = TIME_ORDER.find((t) => baseAnimals.filter((a) => a.activity.includes(t)).length >= 3) || tod;
    }
    this.gameState = { habitat, timeOfDay: tod };
    this.player = { x: 440, y: 310, vx: 0, vy: 0, facing: 0 };
    this.animals = this._initAnimals(habitat);
    this.logged = 0;
    this.bossLogged = false;
    this.integrity = 100;
    this.journal = [];
    this.currentClip = null;
    this.listenActive = false;
    this.listenTicksSession = 0;
    this.recordCount = 0;
    this._isChargingMove = false;
    this._chargeMoveTime = 0;
    this._isDashing = false;
    this._dashEndTime = 0;
    this._wasMouseDown = false;
    this._now = 0;
  }

  _initAnimals(habitat) {
    const base = initAnimals(habitat);
    return base.map((a, i) => {
      const rich = this.speciesList.find((s) => s.id === a.species.id) || a.species;
      return {
        ...a,
        species: { ...a.species, ...rich },
        lastCall: 0,
        bobPhase: i * 1.3,
      };
    });
  }

  tick({ keys = {}, mouse = {}, dt = 1, now = 0 } = {}) {
    this._now = now || this._now + dt * 16;

    let ax = 0;
    let ay = 0;
    if (keys.w || keys.arrowup) ay -= 1;
    if (keys.s || keys.arrowdown) ay += 1;
    if (keys.a || keys.arrowleft) ax -= 1;
    if (keys.d || keys.arrowright) ax += 1;

    if (this.dashEnabled) {
      if (mouse.down && !this._wasMouseDown && !this._isDashing) {
        this._isChargingMove = true;
        this._chargeMoveTime = 0;
      }

      const spaceHeld = !!keys[' '];
      const moveKeysHeld = ax || ay || keys.w || keys.s || keys.a || keys.d;

      if ((mouse.down || (moveKeysHeld && spaceHeld)) && !this._isDashing) {
        this._isChargingMove = true;
        this._chargeMoveTime += dt * 0.04;
        this.player.vx *= 0.65;
        this.player.vy *= 0.65;
      } else if (this._isChargingMove && !mouse.down && !spaceHeld && (this._wasMouseDown || moveKeysHeld)) {
        if (this._chargeMoveTime > 0.35) {
          this._isDashing = true;
          this._dashEndTime = this._now + 650;
          const dir = this.player.facing || Math.atan2(ay || 0, ax || 1);
          const boost = 6.5 + this._chargeMoveTime * 9;
          this.player.vx = Math.cos(dir) * boost;
          this.player.vy = Math.sin(dir) * boost;
        }
        this._isChargingMove = false;
        this._chargeMoveTime = 0;
      }
    } else {
      this._isChargingMove = false;
      this._chargeMoveTime = 0;
      this._isDashing = false;
    }

    if (ax || ay) {
      const len = Math.hypot(ax, ay) || 1;
      this.player.vx += (ax / len) * 3.1 * 0.32;
      this.player.vy += (ay / len) * 3.1 * 0.32;
      this.player.facing = Math.atan2(this.player.vy, this.player.vx);
    }
    this.player.vx *= 0.79;
    this.player.vy *= 0.79;
    this.player.x += this.player.vx * dt;
    this.player.y += this.player.vy * dt;
    this.player.x = Math.max(55, Math.min(825, this.player.x));
    this.player.y = Math.max(75, Math.min(545, this.player.y));

    if (this.dashEnabled && this._isDashing && this._now > this._dashEndTime) this._isDashing = false;

    if (this.dashEnabled && this._isDashing) {
      const dashX = this.player.x;
      const dashY = this.player.y;
      for (const a of this.animals) {
        const dx = a.x - dashX;
        const dy = a.y - dashY;
        const dist = Math.hypot(dx, dy);
        if (dist < 120 && dist > 5) {
          const push = (120 - dist) / 8;
          a.x += (dx / dist) * push;
          a.y += (dy / dist) * push;
        }
      }
    }

    this._wasMouseDown = !!mouse.down;
    this.listenActive = !!(keys.l || keys[' '] || mouse.listenDown || mouse.down);

    const faced = simulateListenFacing(
      { ...this.player, listenActive: this.listenActive },
      this.animals,
      this.gameState.timeOfDay,
      this.listenActive,
    );
    if (this.listenActive) {
      this.player.facing = faced.facing;
      this.listenTicksSession++;
    } else if (mouse.listenDown && (Math.abs(mouse.x - this.player.x) > 8 || Math.abs(mouse.y - this.player.y) > 8)) {
      this.player.facing = Math.atan2(mouse.y - this.player.y, mouse.x - this.player.x);
    }

    for (const a of this.animals) {
      a.bobPhase = (a.bobPhase || 0) + 0.029;
      a.x += Math.sin(a.bobPhase * 0.65) * 0.38;
      a.y += Math.cos(a.bobPhase * 0.48) * 0.27;
    }

    return this.getState();
  }

  /** Scripted dash for sim (gamer segment) — no-op when dash disabled. */
  triggerDash() {
    if (!this.dashEnabled) return this.getState();
    const dir = this.player.facing || 0;
    const boost = 8;
    this.player.vx = Math.cos(dir) * boost;
    this.player.vy = Math.sin(dir) * boost;
    this._isDashing = true;
    this._dashEndTime = this._now + 650;
    this.tick({ keys: {}, mouse: { down: false, listenDown: false, x: this.player.x, y: this.player.y }, dt: 0.5, now: this._now });
  }

  record({ preferBoss = false } = {}) {
    const player = { x: this.player.x, y: this.player.y, facing: this.player.facing, listenActive: this.listenActive };
    let rec = null;
    if (preferBoss || this.needsBossPhase()) {
      const bossId = getBossSpeciesId(this.gameState.habitat);
      const boss = this.animals.find((a) => a.id === bossId);
      if (boss && boss.activity.includes(this.gameState.timeOfDay)) {
        const bestScore = scoreAnimalTarget(player, boss, this.gameState.timeOfDay);
        rec = { dominant: boss, quality: clipQualityFromScore(bestScore), bestScore };
      }
    }
    if (!rec) {
      rec = selectRecordingTarget(player, this.animals, this.gameState.timeOfDay);
    }
    const best = rec.dominant || rec.best;
    this.recordCount++;
    this.currentClip = {
      dominant: best.species,
      dominantAnimal: best,
      quality: rec.quality,
      timeOfDay: this.gameState.timeOfDay,
      habitat: this.gameState.habitat,
      ts: Date.now(),
    };
    return { ...this.currentClip };
  }

  identify(chosenId) {
    if (!this.currentClip) return null;
    const clip = this.currentClip;
    const outcome = applyIdentification({
      chosenId,
      dominantId: clip.dominant.id,
      quality: clip.quality,
      logged: this.logged,
      integrity: this.integrity,
      bossLogged: this.bossLogged,
      habitat: this.gameState.habitat,
    });
    this.logged = outcome.logged;
    this.bossLogged = outcome.bossLogged ?? this.bossLogged;
    this.integrity = outcome.integrity;
    this.journal.unshift({
      species: clip.dominant,
      time: clip.timeOfDay,
      quality: clip.quality,
      correct: outcome.correct,
      guess: outcome.correct ? null : chosenId,
    });
    this.currentClip = null;
    return outcome;
  }

  switchHabitat(habitat) {
    this.gameState.habitat = habitat;
    this.logged = 0;
    this.bossLogged = false;
    this.integrity = 100;
    this.journal = [];
    this.currentClip = null;
    this.recordCount = 0;
    this.listenTicksSession = 0;
    this.animals = this._initAnimals(habitat);
    this.player = { x: 440, y: 310, vx: 0, vy: 0, facing: 0 };
  }

  advanceTime() {
    const idx = TIME_ORDER.indexOf(this.gameState.timeOfDay);
    this.gameState.timeOfDay = TIME_ORDER[(idx + 1) % TIME_ORDER.length];
  }

  /** Sim + UI parity: boss-active time shift and placement when survey target is met. */
  prepareBossPhase() {
    const bossId = getBossSpeciesId(this.gameState.habitat);
    const bossTod = bossId === 'owl' ? 'dusk' : bossId === 'peeper' ? 'night' : 'day';
    this.gameState.timeOfDay = bossTod;
    const bossAnimal = this.animals.find((a) => a.id === bossId);
    if (bossAnimal) {
      bossAnimal.x = 440 + (this.rng() - 0.5) * 70;
      bossAnimal.y = 285 + (this.rng() - 0.5) * 50;
      bossAnimal.lastCall = this._now;
      this.player.x = bossAnimal.x - 55;
      this.player.y = bossAnimal.y - 15;
      this.player.facing = Math.atan2(bossAnimal.y - this.player.y, bossAnimal.x - this.player.x);
      this.listenActive = true;
    }
    return bossId;
  }

  needsBossPhase() {
    return this.logged >= EXPEDITION_REGULAR_TARGET && !this.bossLogged;
  }

  getState() {
    return {
      player: { ...this.player },
      animals: this.animals,
      gameState: { ...this.gameState },
      logged: this.logged,
      bossLogged: this.bossLogged,
      integrity: this.integrity,
      journal: [...this.journal],
      currentClip: this.currentClip ? { ...this.currentClip } : null,
      listenActive: this.listenActive,
      completed: shouldCompleteExpedition(this.logged, this.bossLogged),
      recordCount: this.recordCount,
      listenTicksSession: this.listenTicksSession,
      isDashing: this._isDashing,
      isChargingMove: this._isChargingMove,
      chargeMoveTime: this._chargeMoveTime,
    };
  }
}

  global.EchoesCore = {
    HABITATS: HABITATS,
    PERSONAS: PERSONAS,
    SPECIES: SPECIES,
    TIME_ORDER: TIME_ORDER,
    FACING_BONUS_THRESHOLD: FACING_BONUS_THRESHOLD,
    angleDiff: angleDiff,
    scoreAnimalTarget: scoreAnimalTarget,
    clipQualityFromScore: clipQualityFromScore,
    selectRecordingTarget: selectRecordingTarget,
    facingBonusFromDiff: facingBonusFromDiff,
    computeSnrDb: computeSnrDb,
    computeIdConfidence: computeIdConfidence,
    computeCallWarmth: computeCallWarmth,
    nearestActiveCaller: nearestActiveCaller,
    tickAnimals: tickAnimals,
    applyDashScare: applyDashScare,
    simulateListenFacing: simulateListenFacing,
    initAnimals: initAnimals,
    qualityLabel: qualityLabel,
    integrityGain: integrityGain,
    integrityLoss: integrityLoss,
    applyIdentification: applyIdentification,
    shouldCompleteExpedition: shouldCompleteExpedition,
    getBossSpeciesId: getBossSpeciesId,
    expeditionPhase: expeditionPhase,
    EXPEDITION_REGULAR_TARGET: EXPEDITION_REGULAR_TARGET,
    BOSS_SPECIES_BY_HABITAT: BOSS_SPECIES_BY_HABITAT,
    markHabitatDone: markHabitatDone,
    personaHint: personaHint,
    activeSpeciesForTime: activeSpeciesForTime,
    likelyMatchThreshold: likelyMatchThreshold,
    buildIdentifyOptions: buildIdentifyOptions,
    buildSpectrogramPeaks: buildSpectrogramPeaks,
    SPECIES_FREQ_PROFILES: SPECIES_FREQ_PROFILES,
    SPECIES_LORE: SPECIES_LORE,
    HABITAT_NOISE_FLOOR: HABITAT_NOISE_FLOOR,
    buildPhenologyMatrix: buildPhenologyMatrix,
    suggestPhenologyTime: suggestPhenologyTime,
    buildClipManifest: buildClipManifest,
    dailyRareSpecies: dailyRareSpecies,
    simIdentificationBonus: simIdentificationBonus,
    FieldSession: FieldSession,
  };
})(typeof window !== 'undefined' ? window : globalThis);
